"""事件类型常量。"""

# Session 事件
SESSION_CREATED = "SESSION_CREATED"
SESSION_STARTED = "SESSION_STARTED"
SESSION_SUCCEEDED = "SESSION_SUCCEEDED"
SESSION_FAILED = "SESSION_FAILED"
SESSION_CANCELED = "SESSION_CANCELED"

# Task 事件
TASK_CREATED = "TASK_CREATED"
TASK_STARTED = "TASK_STARTED"
TASK_FINISHED = "TASK_FINISHED"
TASK_FAILED = "TASK_FAILED"

# Agent 事件
AGENT_STARTED = "AGENT_STARTED"
AGENT_WAITING = "AGENT_WAITING"     # agent 调用 spawn_agents 进入 WAITING
AGENT_RESUME = "AGENT_RESUME"       # 子任务全部完成，agent 被唤醒

# Task 执行事件（由 LifecycleManager._execute 发布，供 TaskManager 订阅）
TASK_EXECUTION_FINISHED = "TASK_EXECUTION_FINISHED"
TASK_EXECUTION_FAILED = "TASK_EXECUTION_FAILED"

# Spawn 事件
SPAWN_APPROVED = "SPAWN_APPROVED"
SPAWN_REJECTED = "SPAWN_REJECTED"

# Lifecycle Manager 内部调度事件
LIFECYCLE_TASK_READY = "LIFECYCLE_TASK_READY"          # DAG 依赖满足，进入调度队列
LIFECYCLE_AGENT_SCHEDULED = "LIFECYCLE_AGENT_SCHEDULED"
LIFECYCLE_AGENT_RECYCLED = "LIFECYCLE_AGENT_RECYCLED"

# Tool 事件
TOOL_CALL_STARTED = "TOOL_CALL_STARTED"
TOOL_CALL_FINISHED = "TOOL_CALL_FINISHED"
TOOL_CALL_FAILED = "TOOL_CALL_FAILED"

# Guard 事件
TOKEN_BUDGET_EXCEEDED = "TOKEN_BUDGET_EXCEEDED"
MAX_TURNS_EXCEEDED = "MAX_TURNS_EXCEEDED"
