"""事件类型常量。"""

SESSION_CREATED = 'SESSION_CREATED'
SESSION_STATUS_CHANGED = 'SESSION_STATUS_CHANGED'
TASK_STARTED = 'TASK_STARTED'
TASK_FINISHED = 'TASK_FINISHED'
TOOL_CALL_STARTED = 'TOOL_CALL_STARTED'
TOOL_CALL_FINISHED = 'TOOL_CALL_FINISHED'
